{% set name = "amazon-codewhisperer-jupyterlab-ext" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-codewhisperer-jupyterlab-ext-{{ version }}.tar.gz
  sha256: 0c7893337c024b142cca133d346b1871f4e922120408a85c3908b582fc27a54e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - jupyter_packaging >=0.10,<1.dev0,<2
    - jupyterlab >=4.0,<5.0
    - pip
  run:
    - python >=3.6
    - boto3
    - botocore
    - aiobotocore
    - jupyterlab >=4.0,<5.0

test:
  imports:
    - amazon_codewhisperer_jupyterlab_ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/codewhisperer/
  summary: Amazon CodeWhisperer for JupyterLab
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Amazon CodeWhisperer is an AI coding companion which provides developers 
    with real-time code suggestions in JupyterLab. Individual developers can
    use CodeWhisperer for free in JupyterLab and AWS SageMaker Studio.

extra:
  recipe-maintainers:
    - kumarnzt
    - dhanainme
    - andrewyuq
